/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.mario.mautorun;

import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Mateusz
 */
public class KillLog extends javax.swing.JFrame {

    /**
     * Creates new form KillLog
     */
    public KillLog() {
        initComponents();
        setFont();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(false);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jScrollPane2MouseWheelMoved(evt);
            }
        });
        jScrollPane2.setViewportView(logArea);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 723, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jScrollPane2MouseWheelMoved
        if ((jScrollPane2.getVerticalScrollBar().getMaximum()
                - jScrollPane2.getVerticalScrollBar().getVisibleAmount())
                > jScrollPane2.getVerticalScrollBar().getValue()) {
            logauto = false;
        } else {
            logauto = true;
        }
    }//GEN-LAST:event_jScrollPane2MouseWheelMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        logArea.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    void dodajLog(String msg, SimpleAttributeSet color) {
        try {
            log.insertString(log.getLength(), Main.conf.getTime() + msg + "\n", color);
            if (logauto) {
                logArea.setCaretPosition(log.getLength());
            }
//            PrintWriter chat = null;
//            File fchat = new File(Main.path + "serverLog.txt");
//            if (!fchat.exists()) {
//                fchat.createNewFile();
//            }
//            chat = new PrintWriter(new FileWriter(fchat, true));
//            chat.append(msg + "\n");
//            chat.close();
        } catch (Exception ex) {
            Loggs.loguj("KillLog-dodajLog", ex);
        }
    }
public void setFont() {
        log = logArea.getStyledDocument();
        red = new SimpleAttributeSet();
        boom = new SimpleAttributeSet();
        blue = new SimpleAttributeSet();
        green = new SimpleAttributeSet();
        gray = new SimpleAttributeSet();
        lgray = new SimpleAttributeSet();
        black = new SimpleAttributeSet();
        cyan = new SimpleAttributeSet();
        dgray = new SimpleAttributeSet();
        mag = new SimpleAttributeSet();
        org = new SimpleAttributeSet();
        pink = new SimpleAttributeSet();
        yell = new SimpleAttributeSet();
        white = new SimpleAttributeSet();

        StyleConstants.setForeground(red, Color.RED);
        StyleConstants.setForeground(boom, Color.RED);
        StyleConstants.setForeground(blue, Color.BLUE);
        StyleConstants.setForeground(green, Color.GREEN);
        StyleConstants.setForeground(gray, Color.GRAY);
        StyleConstants.setForeground(lgray, Color.LIGHT_GRAY);
        StyleConstants.setForeground(black, Color.BLACK);
        StyleConstants.setForeground(cyan, Color.CYAN);
        StyleConstants.setForeground(dgray, Color.DARK_GRAY);
        StyleConstants.setForeground(mag, Color.MAGENTA);
        StyleConstants.setForeground(org, Color.ORANGE);
        StyleConstants.setForeground(pink, Color.PINK);
        StyleConstants.setForeground(yell, Color.YELLOW);
        StyleConstants.setForeground(white, Color.WHITE);
        StyleConstants.setBold(boom, true);

    }
private boolean logauto = true;
private StyledDocument log;
SimpleAttributeSet boom;
    SimpleAttributeSet red;
    SimpleAttributeSet blue;
    SimpleAttributeSet green;
    SimpleAttributeSet gray;
    SimpleAttributeSet lgray;
    SimpleAttributeSet black;
    SimpleAttributeSet cyan;
    SimpleAttributeSet dgray;
    SimpleAttributeSet mag;
    SimpleAttributeSet org;
    SimpleAttributeSet pink;
    SimpleAttributeSet yell;
    SimpleAttributeSet white;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane logArea;
    // End of variables declaration//GEN-END:variables
}
